apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: hamamooz
  namespace: monitoring-hamamooz-task
spec:
  retentionPeriod: "3d"
  removePvcAfterDelete: false
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi
  nodeSelector:
    hamamooz.io/workload-node: "true"
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: hamamooz
  namespace: monitoring-hamamooz-task
spec:
  replicaCount: 1
  selectAllByDefault: false
  serviceScrapeSelector:
    matchLabels:
      pipeline: hamamooz
  remoteWrite:
    - url: http://vmsingle-hamamooz.monitoring-hamamooz-task.svc:8428/api/v1/write
  scrapeInterval: 15s
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  nodeSelector:
    hamamooz.io/workload-node: "true"
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: hamamooz-backend
  namespace: monitoring-hamamooz-task
  labels:
    pipeline: hamamooz
spec:
  namespaceSelector:
    matchNames:
      - hemmasian
  selector:
    matchLabels:
      observability: hamamooz
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
