apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: hamamooz
  namespace: monitoring-hamamooz-task
spec:
  replicaCount: 1
  userSelector:
    matchLabels:
      access: hamamooz
  userNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: monitoring-hamamooz-task
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
  nodeSelector:
    hamamooz.io/workload-node: "true"
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: hamamooz-reader
  namespace: monitoring-hamamooz-task
  labels:
    access: hamamooz
spec:
  username: hamamooz-reader
  passwordRef:
    name: vmauth-reader-credentials
    key: password
  targetRefs:
    - crd:
        kind: VMSingle
        name: hamamooz
        namespace: monitoring-hamamooz-task
      paths:
        - /vmui.*
        - /api/v1/query.*
        - /api/v1/label.*
        - /api/v1/series.*
        - /api/v1/metadata.*
        - /api/v1/status.*
