apiVersion: v1
kind: Service
metadata:
  name: vmsingle-hamamooz-nodeport
  namespace: monitoring-hamamooz-task
  labels:
    app.kubernetes.io/name: vmsingle
    app.kubernetes.io/part-of: hamamooz
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: hamamooz
    app.kubernetes.io/name: vmsingle
    managed-by: vm-operator
  ports:
    - name: http
      port: 8428
      targetPort: 8429
      nodePort: 30428
