apiVersion: v1
kind: Pod
metadata:
  name: backend-data-loader
  namespace: hemmasian
spec:
  restartPolicy: Never
  containers:
    - name: loader
      image: hemmasian-backend:1.0.0
      imagePullPolicy: Never
      command: ["/bin/sh", "-c", "sleep 3600"]
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: data
          mountPath: /data
        - name: backups
          mountPath: /backups
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: backend-data
    - name: backups
      persistentVolumeClaim:
        claimName: backend-backups
