# Generated by Django 5.2.17 on 2026-08-22 21:25

import backups.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0002_namespace_app_namespace_unique_namespace_per_cluster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.CharField(default=backups.models.generate_backup_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('source_path', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('output_path', models.CharField(blank=True, default='', max_length=1500)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='clusters.app')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.CharField(default=backups.models.generate_schedule_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('source_path', models.CharField(max_length=1000)),
                ('cron_expression', models.CharField(max_length=100)),
                ('periodic_task_name', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedules', to='clusters.app')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
