apiVersion: 1

datasources:
  - name: Prometheus
    uid: PBFA97CFB590B2093
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: VictoriaMetrics
    uid: P4169E866C3094E38
    type: prometheus
    access: proxy
    url: http://minikube:30428
    isDefault: false
    editable: false
