# Generated by Django 5.2.17 on 2026-08-18 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('status', models.CharField(default='Active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespaces', to='clusters.cluster')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('image', models.CharField(max_length=500)),
                ('replicas', models.PositiveIntegerField(default=1)),
                ('cpu_request', models.CharField(blank=True, default='', max_length=32)),
                ('memory_request', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='clusters.namespace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='namespace',
            constraint=models.UniqueConstraint(fields=('cluster', 'name'), name='unique_namespace_per_cluster'),
        ),
        migrations.AddConstraint(
            model_name='app',
            constraint=models.UniqueConstraint(fields=('namespace', 'name'), name='unique_app_per_namespace'),
        ),
    ]
